@startuml

title __ROAD's Class Diagram__\n

  namespace com.javarush.games.racer {
    namespace road {
      class com.javarush.games.racer.road.Car {
          + Car()
      }
    }
  }
  

  namespace com.javarush.games.racer {
    namespace road {
      class com.javarush.games.racer.road.MovingCar {
          - dx : int
          + MovingCar()
          + move()
          - checkRoadHit()
      }
    }
  }
  

  namespace com.javarush.games.racer {
    namespace road {
      class com.javarush.games.racer.road.RoadManager {
          {static} + LEFT_BORDER : int
          {static} + RIGHT_BORDER : int
          {static} - FIRST_LANE_POSITION : int
          {static} - FOURTH_LANE_POSITION : int
          {static} - PLAYER_CAR_DISTANCE : int
          - items : List<RoadObject>
          - passedCarsCount : int
          + checkCrush()
          + draw()
          + generateNewRoadObjects()
          + getPassedCarsCount()
          + move()
          - addRoadObject()
          - createRoadObject()
          - deletePassedItems()
          - generateMovingCar()
          - generateRegularCar()
          - generateThorn()
          - isMovingCarExists()
          - isRoadSpaceFree()
          - isThornExists()
      }
    }
  }
  

  namespace com.javarush.games.racer {
    namespace road {
      class com.javarush.games.racer.road.RoadObject {
          + speed : int
          + RoadObject()
          {static} + getHeight()
          + isCollisionWithDistance()
          + move()
          {static} - getMatrix()
      }
    }
  }
  

  namespace com.javarush.games.racer {
    namespace road {
      enum RoadObjectType {
        BUS
        CAR
        DRUNK_CAR
        SPORT_CAR
        THORN
        TRUCK
      }
    }
  }
  

  namespace com.javarush.games.racer {
    namespace road {
      class com.javarush.games.racer.road.Thorn {
          + Thorn()
      }
    }
  }
  

  com.javarush.games.racer.road.Car -up-|> com.javarush.games.racer.road.RoadObject
  com.javarush.games.racer.road.MovingCar -up-|> com.javarush.games.racer.road.RoadObject
  com.javarush.games.racer.road.RoadObject -up-|> com.javarush.games.racer.GameObject
  com.javarush.games.racer.road.RoadObject o-- com.javarush.games.racer.road.RoadObjectType : type
  com.javarush.games.racer.road.Thorn -up-|> com.javarush.games.racer.road.RoadObject


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
